# Generated by Django 3.2.7 on 2021-09-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photograph', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='date',
            new_name='date_from',
        ),
        migrations.AddField(
            model_name='collection',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
